Repository hellokitty-coding-club/LGTM-Backend, pull requests merged in 2023-09, with the labels that each got.

#75 mission detail api 수정사항 반영
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/domain/mapper/MissionMapper.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/dto/MissionDetailViewResponse.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/mission/controller/GetMissionTest.java
Labels: :fire: hot-fix

#82 fix: add mock token creator in test code
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/member/controller/UpdateDeviceTokenControllerTest.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/mission/controller/CreateMissionTest.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/mission/controller/GetMissionTest.java
Labels: :fire: hot-fix

#84 fix #10: edit request body policy
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/dto/CreateMissionRequest.java
Labels: 🐛 bug, :hammer: fix

#85 fix #62: fix cacheable key parameter name
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/repository/MissionCustomRepositoryImpl.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/repository/MissionScrapRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/repository/MissionViewRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/tag/repository/TechTagPerMissionRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/tag/repository/TechTagRepository.java
Labels: 💫 feat, :hammer: fix

#86 Member 프로필 조회 API
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/controller/MemberController.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/domain/mapper/MemberMapper.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/dto/JuniorDetailInfo.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/dto/MemberDetailInfo.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/dto/MemberDetailProfile.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/dto/SeniorDetailInfo.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/repository/JuniorRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/service/MemberService.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/domain/mapper/MissionMapper.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/repository/MissionRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/repository/MissionRegistrationRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/tag/repository/TechTagPerMemberRepository.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/member/controller/GetMemberProfileTest.java
Labels: 💫 feat

#88 hotfix: memberType 추가
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/controller/MemberController.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/domain/mapper/MemberMapper.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/dto/MemberDetailProfile.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/service/MemberService.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/member/controller/GetMemberProfileTest.java
Labels: :fire: hot-fix

#90 feat #89: add icon img url
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/repository/MissionRegistrationRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/tag/domain/TechTag.java
Labels: :hammer: fix

#83 senior dashboard detail view
  API-Server/src/main/java/swm/hkcc/LGTM/app/global/constant/ResponseCode.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/controller/RegistrationController.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/domain/ProcessStatus.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/domain/additionalInfoProvider/AdditionalInfoProvider.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/domain/additionalInfoProvider/AdditionalInfoProviderFactory.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/domain/additionalInfoProvider/DefaultInfoProvider.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/domain/additionalInfoProvider/FeedbackInfoProvider.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/domain/additionalInfoProvider/PaymentInfoProvider.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/domain/additionalInfoProvider/PullRequestInfoProvider.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/domain/mapper/RegistrationMapper.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/MemberRegisterSimpleInfo.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/MissionHistoryInfo.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/registrationSeniorDetailResponse/AdditionalFeedbackInfo.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/registrationSeniorDetailResponse/AdditionalInfo.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/registrationSeniorDetailResponse/AdditionalPayInfo.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/registrationSeniorDetailResponse/AdditionalPullRequestInfo.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/registrationSeniorDetailResponse/RegistrationSeniorDetailFeedbackResponse.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/registrationSeniorDetailResponse/RegistrationSeniorDetailPayResponse.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/registrationSeniorDetailResponse/RegistrationSeniorDetailPullRequestResponse.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/registrationSeniorDetailResponse/RegistrationSeniorDetailResponse.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/exception/NotRegisteredMission.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/mapper/RegistrationMapper.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/repository/MissionRegistrationCustomRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/repository/MissionRegistrationCustomRepositoryImpl.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/repository/MissionRegistrationRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/service/RegistrationService.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/review/repository/ReviewRepository.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/registration/controller/RegistrationMissionControllerTest.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/registration/controller/SeniorDashboardControllerTest.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/registration/controller/SeniorDashboardDetailControllerTest.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/registration/service/SeniorEnrollDetailServiceTest.java
Labels: 💫 feat

#94 junior mission dashboard api
  API-Server/src/main/java/swm/hkcc/LGTM/app/global/constant/ResponseCode.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/service/MemberValidator.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/controller/RegistrationController.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/domain/additionalInfoProvider/JuniorAccountInfoProvider.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/domain/additionalInfoProvider/JuniorDefaultInfoProvider.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/domain/additionalInfoProvider/JuniorFeedbackInfoProvider.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/domain/additionalInfoProvider/JuniorInfoProvider.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/domain/additionalInfoProvider/JuniorInfoProviderFactory.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/domain/additionalInfoProvider/JuniorPullRequestInfoProvider.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/domain/mapper/RegistrationMapper.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/MemberRegisterSimpleInfo.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/MissionHistoryInfo.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/registrationJuniorResponse/JuniorAdditionalAccountInfo.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/registrationJuniorResponse/JuniorAdditionalFeedbackInfo.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/registrationJuniorResponse/JuniorAdditionalInfo.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/registrationJuniorResponse/JuniorAdditionalPullRequestInfo.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/registrationJuniorResponse/RegistrationJuniorAccountResponse.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/registrationJuniorResponse/RegistrationJuniorFeedbackResponse.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/registrationJuniorResponse/RegistrationJuniorPullRequestResponse.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/registrationJuniorResponse/RegistrationJuniorResponse.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/exception/NotRegisteredMissionInternal.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/repository/MissionRegistrationCustomRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/repository/MissionRegistrationCustomRepositoryImpl.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/repository/MissionRegistrationRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/service/RegistrationService.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/service/RegistrationValidator.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/review/exception/NotExistReviewInternal.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/registration/controller/JuniorDashboardControllerTest.java
Labels: 💫 feat

#98 Feature/hotfix signin
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/domain/Junior.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/domain/Member.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/domain/Senior.java
Labels: 🐛 bug, :fire: hot-fix

#97 미션 진행 버튼 api
  API-Server/src/main/java/swm/hkcc/LGTM/app/global/constant/ResponseCode.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/service/MemberValidator.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/service/CreateMissionServiceImpl.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/utils/GithubUrlValidator.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/controller/RegistrationController.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/domain/MissionHistory.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/domain/MissionRegistration.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/domain/ProcessStatus.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/MissionHistoryInfo.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/PullRequestRegisterRequest.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/exception/InvalidProcessStatus.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/service/RegistrationService.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/registration/controller/CompleteReviewControllerTest.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/registration/controller/ConfirmPaymentControllerTest.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/registration/controller/RegisterPaymentControllerTest.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/registration/controller/RegisterPullRequestControllerTest.java
Labels: 💫 feat
