Repository hellokitty-coding-club/LGTM-Backend, pull requests merged in 2023-10, with the labels that each got.

#100 미션 삭제 api
  API-Server/src/main/java/swm/hkcc/LGTM/app/global/constant/ResponseCode.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/controller/MissionController.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/exception/ImpossibleToDeleteMission.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/service/DeleteMissionService.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/repository/MissionRegistrationRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/tag/repository/TechTagPerMissionRepository.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/mission/controller/DeleteMissionControllerTest.java
Labels: 💫 feat

#104 junior dashboard 수정사항 반영
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/domain/additionalInfoProvider/JuniorAccountInfoProvider.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/registrationJuniorResponse/JuniorAdditionalPullRequestInfo.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/registrationJuniorResponse/RegistrationJuniorPullRequestResponse.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/registration/controller/JuniorDashboardControllerTest.java
Labels: ⚙️ chore, :hammer: fix

#106 junior dashboard api : 요구사항 수정
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/registrationJuniorResponse/RegistrationJuniorResponse.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/registrationSeniorDetailResponse/RegistrationSeniorDetailResponse.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/registration/controller/JuniorDashboardControllerTest.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/registration/controller/SeniorDashboardDetailControllerTest.java
Labels: 💫 feat, :hammer: fix

#52 Grouping A/B Test User - used in SDUI
  API-Server/src/main/java/swm/hkcc/LGTM/app/global/constant/ResponseCode.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/constant/HomeServerDrivenUISequenceByVersion.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/constant/MissionContentType.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/controller/HomeController.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/domain/holder/MissionItemHolder.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/domain/serverDrivenUI/HomeServerDrivenUISequenceFactory.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/domain/serverDrivenUI/MissionProcessServerDrivenUISequenceFactory.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/service/HomeService.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/service/HomeServiceImpl.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/serverDrivenUI/ServerDrivenContent.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/serverDrivenUI/constant/ABTest.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/serverDrivenUI/constant/Theme.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/serverDrivenUI/constant/ViewType.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/serverDrivenUI/domain/ABTestService.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/serverDrivenUI/domain/ABTestUserGroup.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/serverDrivenUI/domain/ABTestUserGroupRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/serverDrivenUI/domain/ServerDrivenUISequenceFactory.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/serverDrivenUI/exception/UserABTestGroupNotFound.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/mission/domain/holder/MissionItemHolderTest.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/mission/domain/serverDrivenUI/HomeServerDrivenUISequenceFactoryTest.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/mission/service/HomeServiceImplTest.java
Labels: ♻️ refactor, 💫 feat

#109 요구사항 수정 Feature/#67 junior dashboard
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/domain/ProcessStatus.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/domain/mapper/RegistrationMapper.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/registrationJuniorResponse/JuniorAdditionalAccountInfo.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/registrationJuniorResponse/JuniorAdditionalFeedbackInfo.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/registrationJuniorResponse/JuniorAdditionalInfo.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/registrationJuniorResponse/JuniorAdditionalPullRequestInfo.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/registrationJuniorResponse/RegistrationJuniorAccountResponse.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/registrationJuniorResponse/RegistrationJuniorFeedbackResponse.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/registrationJuniorResponse/RegistrationJuniorPullRequestResponse.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/registrationJuniorResponse/RegistrationJuniorResponse.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/registrationSeniorDetailResponse/AdditionalFeedbackInfo.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/registrationSeniorDetailResponse/AdditionalInfo.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/registrationSeniorDetailResponse/AdditionalPayInfo.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/registrationSeniorDetailResponse/AdditionalPullRequestInfo.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/registrationSeniorDetailResponse/RegistrationSeniorDetailFeedbackResponse.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/registrationSeniorDetailResponse/RegistrationSeniorDetailPayResponse.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/registrationSeniorDetailResponse/RegistrationSeniorDetailPullRequestResponse.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/dto/registrationSeniorDetailResponse/RegistrationSeniorDetailResponse.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/registration/controller/JuniorDashboardControllerTest.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/registration/controller/SeniorDashboardDetailControllerTest.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/registration/service/SeniorEnrollDetailServiceTest.java
Labels: :hammer: fix

#113 Feature/#108 mission recommendation
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/controller/HomeController.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/domain/MissionRecommendation.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/repository/MissionCustomRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/repository/MissionCustomRepositoryImpl.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/repository/MissionRecommendationRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/service/MissionServiceImpl.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/mission/service/MissionServiceImplTest.java
Labels: 💫 feat

#121 알림센터 조회 API
  API-Server/src/main/java/swm/hkcc/LGTM/app/global/api/IntroController.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/global/notification/dto/NotificationDTO.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/notification/controller/NotificationCenterController.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/notification/domain/Notification.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/notification/dto/NotificationDTO.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/notification/repository/NotificationRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/notification/service/NotificationCenterService.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/notification/service/NotificationService.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/notification/service/NotificationServiceImpl.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/notification/service/RegistrationNotificationAopConfig.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/global/api/IntroControllerTest.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/global/api/IntroPushControllerTest.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/global/notification/controller/NotificationCenterControllerTest.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/global/notification/service/NotificationServiceMock.java
Labels: 💫 feat
