Repository hellokitty-coding-club/LGTM-Backend, pull requests merged in 2023-08, with the labels that each got.

#34 Improve Home Screen API Performance using Redis Cache
  API-Server/build.gradle
  API-Server/src/main/java/swm/hkcc/LGTM/app/global/cache/CacheKey.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/global/cache/TTLKey.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/domain/Authority.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/domain/Junior.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/domain/Member.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/domain/Senior.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/domain/Mission.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/repository/MissionCustomRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/repository/MissionCustomRepositoryImpl.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/repository/MissionScrapRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/repository/MissionViewRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/service/MissionServiceImpl.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/domain/MissionRegistration.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/repository/MissionRegistrationRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/tag/domain/TechTag.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/tag/repository/TechTagPerMissionRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/tag/repository/TechTagRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/config/RedisConfig.java
  API-Server/src/main/resources/application-dev.yml
  API-Server/src/main/resources/application-prod.yml
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/mission/repository/MissionCustomRepositoryImplTest.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/mission/service/MissionServiceImplTest.java
  API-Server/src/test/java/swm/hkcc/LGTM/config/EmbeddedRedisConfig.java
  API-Server/src/test/java/swm/hkcc/LGTM/config/RedisConfigTest.java
Labels: 🗃 infra, ♻️ refactor, 💫 feat

#24 Feature/#11 home v1 with server driven UI
  API-Server/build.gradle
  API-Server/src/main/java/swm/hkcc/LGTM/app/global/cache/CacheKey.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/global/cache/TTLKey.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/domain/Authority.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/domain/Junior.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/domain/Member.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/domain/Senior.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/constant/HomeServerDrivenUISequenceByVersion.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/constant/MissionContentType.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/controller/HomeController.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/domain/Mission.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/domain/MissionContentData.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/domain/MissionContentSequence.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/domain/holder/MissionItemHolder.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/domain/mapper/MissionMapper.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/domain/serverDrivenUI/HomeServerDrivenUISequenceFactory.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/domain/serverDrivenUI/MissionProcessServerDrivenUISequenceFactory.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/dto/MissionDetailsDto.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/dto/MissionDto.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/dto/MissionTitleDto.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/repository/MissionCustomRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/repository/MissionCustomRepositoryImpl.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/repository/MissionRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/repository/MissionScrapRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/repository/MissionViewRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/service/HomeService.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/service/HomeServiceImpl.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/service/MissionService.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/service/MissionServiceImpl.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/domain/MissionRegistration.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/domain/PersonalStatus.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/repository/MissionRegistrationRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/serverDrivenUI/ServerDrivenContent.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/serverDrivenUI/ServerDrivenContents.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/serverDrivenUI/ServerDrivenScreenResponse.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/serverDrivenUI/ServerDrivenUISequenceByVersion.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/serverDrivenUI/Theme.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/serverDrivenUI/ViewType.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/serverDrivenUI/domain/ServerDrivenUISequenceFactory.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/tag/domain/TechTag.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/tag/repository/TechTagPerMissionRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/tag/repository/TechTagRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/config/RedisConfig.java
  API-Server/src/main/java/swm/hkcc/LGTM/config/SecurityConfig.java
  API-Server/src/main/resources/application-dev.yml
  API-Server/src/main/resources/application-prod.yml
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/mission/domain/holder/MissionItemHolderTest.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/mission/domain/mapper/MissionMapperTest.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/mission/domain/serverDrivenUI/HomeServerDrivenUISequenceFactoryTest.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/mission/repository/MissionCustomRepositoryImplTest.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/mission/service/HomeServiceImplTest.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/mission/service/MissionServiceImplTest.java
  API-Server/src/test/java/swm/hkcc/LGTM/config/EmbeddedRedisConfig.java
  API-Server/src/test/java/swm/hkcc/LGTM/config/RedisConfigTest.java
Labels: 💫 feat

#16 Feature #10 - create mission
  .github/workflows/buildImageOnDispatch.yml
  API-Server/src/main/java/swm/hkcc/LGTM/app/global/constant/ResponseCode.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/exception/NotJuniorMember.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/exception/NotSeniorMember.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/service/MemberValidator.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/controller/CreateMissionController.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/domain/Mission.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/domain/MissionStatus.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/dto/CreateMissionRequest.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/dto/CreateMissionResponse.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/service/CreateMissionService.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/service/CreateMissionServiceImpl.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/tag/repository/TechTagPerMissionRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/tag/service/TechTagService.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/tag/service/TechTagValidator.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/mission/controller/CreateMissionTest.java
Labels: 💫 feat

#55 Hotfix mission entity
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/domain/Mission.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/dto/CreateMissionRequest.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/repository/MissionCustomRepositoryImpl.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/mission/controller/CreateMissionTest.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/mission/domain/mapper/MissionMapperTest.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/mission/repository/MissionCustomRepositoryImplTest.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/mission/service/MissionServiceImplTest.java
Labels: :fire: hot-fix

#58 Get Mission detail api
  API-Server/src/main/java/swm/hkcc/LGTM/app/global/constant/ResponseCode.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/auth/service/AuthServiceImpl.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/repository/SeniorRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/service/MemberService.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/controller/MissionController.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/domain/mapper/MissionMapper.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/dto/MemberProfile.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/dto/MissionDetailViewResponse.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/exception/NotExistMission.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/service/MissionService.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/service/MissionServiceImpl.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/mission/controller/GetMissionTest.java
Labels: 💫 feat

#60 #53: 오타 수정
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/domain/mapper/MissionMapper.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/mission/controller/GetMissionTest.java
Labels: :fire: hot-fix

#50 Feature/#10 create mission
  API-Server/src/main/java/swm/hkcc/LGTM/app/global/constant/ResponseCode.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/controller/MissionController.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/domain/Mission.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/dto/CreateMissionRequest.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/exception/InvalidGithubUrl.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/service/CreateMissionService.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/service/CreateMissionServiceImpl.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/mission/controller/CreateMissionTest.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/mission/domain/mapper/MissionMapperTest.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/mission/repository/MissionCustomRepositoryImplTest.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/mission/service/MissionServiceImplTest.java
Labels: ♻️ refactor, :hammer: fix
