Repository hellokitty-coding-club/LGTM-Backend, pull requests merged in 2023-07, with the labels that each got.

#5 Feature #2 - Sign in & Sign up with Github Oauth
  API-Server/.gitignore
  API-Server/Dockerfile
  API-Server/build.gradle
  API-Server/src/main/java/swm/hkcc/LGTM/LgtmApplication.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/global/advice/ApiExceptionHandler.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/global/api/IntroController.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/global/constant/ResponseCode.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/global/entity/BaseEntity.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/auth/constants/TokenType.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/auth/controller/AuthController.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/auth/controller/OauthController.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/auth/dto/oauth/GithubOAuthRequest.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/auth/dto/oauth/GithubOAuthResponse.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/auth/dto/oauth/GithubUserInfo.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/auth/dto/signIn/GithubSignInRequest.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/auth/dto/signIn/SignInResponse.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/auth/dto/signUp/CommonUserData.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/auth/dto/signUp/JuniorSignUpRequest.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/auth/dto/signUp/SeniorSignUpRequest.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/auth/dto/signUp/SignUpResponse.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/auth/exception/DuplicateNickName.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/auth/exception/InvalidGithubAccessToken.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/auth/exception/InvalidTechTag.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/auth/service/AuthService.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/auth/service/AuthServiceImpl.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/auth/utils/GithubUserInfoProvider.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/auth/utils/jwt/JwtAccessDeniedHandler.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/auth/utils/jwt/JwtAuthenticationEntryPoint.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/auth/utils/jwt/JwtFilter.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/auth/utils/jwt/TokenProvider.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/domain/Authority.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/domain/Bank.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/domain/CareerAuth.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/domain/CertificationStatus.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/domain/Junior.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/domain/Member.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/domain/Senior.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/domain/custom/CustomUserDetails.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/exception/InvalidBankName.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/exception/InvalidCareerPeriod.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/repository/JuniorRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/repository/MemberRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/repository/SeniorRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/service/CustomUserDetailsService.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/tag/domain/TechTag.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/tag/domain/TechTagPerMember.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/tag/repository/TechTagPerMemberRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/tag/repository/TechTagRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/config/JpaConfig.java
  API-Server/src/main/java/swm/hkcc/LGTM/config/JwtSecurityConfig.java
  API-Server/src/main/java/swm/hkcc/LGTM/config/SecurityConfig.java
  API-Server/src/main/resources/application-dev.yml
  API-Server/src/main/resources/application-prod.yml
  API-Server/src/main/resources/application.properties
  API-Server/src/main/resources/application.yml
  API-Server/src/test/java/swm/hkcc/LGTM/LgtmApplicationTests.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/auth/controller/AuthControllerTest.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/auth/controller/OauthControllerTest.java
Labels: 💫 feat

#6 Feature #3 - Document setting
  API-Server/build.gradle
  API-Server/src/docs/asciidoc/index.adoc
  API-Server/src/test/java/swm/hkcc/LGTM/LgtmApplicationTests.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/global/api/IntroControllerTest.java
  API-Server/src/test/resources/org/springframework/restdocs/templates/asciidoctor/request-fields.snippet
  API-Server/src/test/resources/org/springframework/restdocs/templates/asciidoctor/response-fields.snippet
Labels: 📝 docs

#9 Document setting - Swagger UI setting
  API-Server/build.gradle
  API-Server/src/docs/asciidoc/index.adoc
  API-Server/src/main/java/swm/hkcc/LGTM/config/SecurityConfig.java
  API-Server/src/main/resources/application.yml
  API-Server/src/test/java/swm/hkcc/LGTM/app/global/api/IntroControllerTest.java
Labels: 📝 docs

#14 Refactoring CustomUserDetails & TokenProvider with Authentication
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/auth/service/AuthServiceImpl.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/auth/utils/jwt/TokenProvider.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/domain/Member.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/repository/MemberRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/service/CustomUserDetailsService.java
  API-Server/src/main/java/swm/hkcc/LGTM/config/SecurityConfig.java
Labels: 🐛 bug, ♻️ refactor

#18 #17: SignInResponse에 github profile image url과 member type(junior…
  API-Server/src/main/java/swm/hkcc/LGTM/app/global/constant/ResponseCode.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/auth/dto/signIn/SignInResponse.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/auth/exception/UnspecifiedMemberType.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/auth/service/AuthServiceImpl.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/repository/JuniorRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/repository/SeniorRepository.java
Labels: 🐛 bug, 💫 feat

#22 feature #20 - validation exception
  API-Server/src/main/java/swm/hkcc/LGTM/app/global/advice/ApiExceptionHandler.java
Labels: 💫 feat, :hammer: fix
