Repository hellokitty-coding-club/LGTM-Backend, pull requests merged in 2023-11, with the labels that each got.

#123 fix #107: edit noti target id
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/notification/service/RegistrationNotificationAopConfig.java
Labels: :hammer: fix

#124 home api v3
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/controller/HomeController.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/serverDrivenUI/domain/ABTestService.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/serverDrivenUI/domain/groupAssignment/ABTestService.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/serverDrivenUI/domain/groupAssignment/HomeScreenABTestService.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/serverDrivenUI/domain/groupAssignment/strategy/GroupAssignmentStrategy.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/serverDrivenUI/domain/groupAssignment/strategy/ModuloBasedGroupAssignmentStrategy.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/serverDrivenUI/domain/groupAssignment/strategy/RandomGroupAssignmentStrategy.java
Labels: ♻️ refactor, 💫 feat

#126 Feature/#125 notification center
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/notification/controller/NotificationCenterController.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/notification/dto/NewNotificationDTO.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/notification/repository/NotificationCustomRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/notification/repository/NotificationCustomRepositoryImpl.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/notification/repository/NotificationRepository.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/notification/service/NotificationCenterService.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/notification/controller/NewNotificationControllerTest.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/notification/controller/NotificationCenterControllerTest.java
  API-Server/src/test/java/swm/hkcc/LGTM/app/modules/notification/service/NotificationServiceMock.java
Labels: 💫 feat

#129 미션생성 기능 수정
  API-Server/src/main/java/swm/hkcc/LGTM/app/global/advice/ApiExceptionHandler.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/domain/Mission.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/dto/CreateMissionRequest.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/service/CreateMissionServiceImpl.java
Labels: ♻️ refactor, :hammer: fix

#130 fix #67: edit account holder name
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/domain/additionalInfoProvider/JuniorAccountInfoProvider.java
Labels: :hammer: fix

#133 미션 참가인원 -> @CacheEvict 를 사용하여 미션 등록 시마다 인원 정보 캐시 초기화
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/service/RegistrationService.java
Labels: :hammer: fix

#134 Feature/#122 home api v3
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/member/service/MemberService.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/constant/HomeServerDrivenUISequenceByVersion.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/constant/MissionContentType.java
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/registration/repository/MissionRegistrationRepository.java
Labels: :hammer: fix

#138 Fix/#137 redis refactor
  API-Server/src/main/java/swm/hkcc/LGTM/config/RedisClusterConfig.java
  API-Server/src/main/java/swm/hkcc/LGTM/config/RedisConfig.java
  API-Server/src/main/resources/application-dev.yml
  API-Server/src/main/resources/application-prod.yml
  API-Server/src/main/resources/application.yml
Labels: 🗃 infra, :hammer: fix

#143 fix : 핫한미션 요구사항 수정
  API-Server/src/main/java/swm/hkcc/LGTM/app/modules/mission/domain/holder/MissionItemHolder.java
Labels: :hammer: fix
